# Generated by Django 5.0.3 on 2024-03-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mywishlist',
        ),
    ]
