# Generated by Django 4.2.7 on 2023-12-05 05:37

import Ecommerceapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ecommerceapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorie",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="main_categorie",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="sub_categorie",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="variant_image",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=Ecommerceapp.models.Variant_image.get_upload_path,
            ),
        ),
    ]
