# Generated by Django 4.2.7 on 2024-01-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ecommerceapp", "0004_product_rating_delete_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
