# Generated by Django 4.2.7 on 2024-01-30 09:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Ecommerceapp", "0005_product_color_product_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Availability",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="Category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Ecommerceapp.categorie",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="Description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="Discount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="Product_info",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="Section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Ecommerceapp.section",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="model_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="total_quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product_image",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Product_images"),
        ),
        migrations.AlterField(
            model_name="product_image",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Ecommerceapp.product",
            ),
        ),
    ]
