# Generated by Django 5.0.3 on 2024-03-30 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0008_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewed',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='viewed',
            unique_together={('user', 'product')},
        ),
        migrations.AddField(
            model_name='viewed',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='recently_viewed_images'),
        ),
        migrations.AlterField(
            model_name='viewed',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='viewed',
            name='image',
        ),
    ]
