# Generated by Django 5.0.3 on 2024-03-30 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0009_alter_viewed_options_alter_viewed_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewed',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.AlterUniqueTogether(
            name='viewed',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='viewed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recently_viewed_images/'),
        ),
        migrations.AlterField(
            model_name='viewed',
            name='viewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='viewed',
            name='product_image',
        ),
    ]
