# Generated by Django 5.0.3 on 2024-04-03 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0011_mylist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='viewed',
        ),
    ]
