# Generated by Django 5.0.3 on 2024-04-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0012_delete_viewed'),
    ]

    operations = [
    ]
