# Generated by Django 5.0.3 on 2024-04-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0013_auto_20240403_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal_of_the_day',
            name='deal_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cod',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
