# Generated by Django 4.2.7 on 2023-12-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CART", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="tax",
            field=models.FloatField(default=1, null=True),
        ),
    ]
