# Generated by Django 5.0.3 on 2024-03-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CART', '0002_alter_cartitem_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
